import TanstackProvider from "@/utils/Provider/TanstackProvider";
import "./globals.css";
import { Toaster } from "sonner";
import PropertyTypesProvider from "./_context/PropertyTypesContext";
import StatesProvider from "./_context/StatesContext";
import PropertyStatusesProvider from "./_context/PropertyStatusesContext";
import RolesProvider from "./_context/RolesContext";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <TanstackProvider>
          <PropertyTypesProvider>
            <StatesProvider>
              <PropertyStatusesProvider>
                <RolesProvider>
                  <>{children}</>
                </RolesProvider>
              </PropertyStatusesProvider>
            </StatesProvider>
          </PropertyTypesProvider>
        </TanstackProvider>
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
