import TanstackProvider from "@/utils/Provider/TanstackProvider";
import "./globals.css";
import { Toaster } from "sonner";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <TanstackProvider>
          <>{children}</>
        </TanstackProvider>
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
